### ISSUE TITLE
Block Suspicious Network Communication and Netcat Listener

### ISSUE THREAD

**Issue by ksoc-automator** [rad-security/kbom#155]
## Description
Security monitoring has detected suspicious network activity in the EKS cluster `rad-demos-public-4cf14c07`:
1. A `netcat-listener` deployment in the `detection-demo` namespace is using port 4444, commonly associated with backdoors and C2 channels
2. The `ssrf-vulnerable-app` deployment is making unrestricted outbound connections that could be exploited for data exfiltration

## Proposed Solution
1. Immediately terminate the `netcat-listener` deployment
2. Implement network egress controls for `ssrf-vulnerable-app` to:
   - Only allow connections to authorized destinations (PyPI registry)
   - Block all other outbound traffic
3. Deploy the following network policy to restrict the netcat container:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-netcat
  namespace: detection-demo
spec:
  podSelector:
    matchLabels:
      app: netcat-listener
  policyTypes:
  - Ingress
  - Egress
```

## Impact
- Critical: The netcat listener could be used as a backdoor into the cluster
- High: SSRF vulnerabilities could be exploited for data exfiltration and lateral movement

## Tasks
- [ ] Investigate why the netcat listener was deployed and by whom
- [ ] Remove the netcat deployment
- [ ] Implement network policies to restrict outbound traffic
- [ ] Create alerts for any future attempts to deploy similar tools
- [ ] Review audit logs for any signs of exploitation

## Related Data
Finding ID: 9f537a6b86a005eaec11f6abf25807259504bb6750a44e7ac2ec1e14ce18488e
