### ISSUE TITLE
Implement Kubernetes Network Policies Based on Observed Traffic Patterns

### ISSUE THREAD

**Issue by ksoc-automator** [rad-security/kbom#161]
## Description
Runtime analysis has revealed specific network traffic patterns in the EKS cluster `rad-demos-public-4cf14c07`, particularly in the `detection-demo` namespace. Current network controls do not adequately restrict or monitor this traffic, leaving the cluster vulnerable to lateral movement and data exfiltration.

## Observed Traffic Patterns
1. Internal pod-to-pod communication on ports 80 and 8080
2. Non-standard communication on port 4444 via netcat
3. External communication to PyPI registry (151.101.x.x) on port 443
4. Various internal communications on the 10.0.0.0/8 network

## Proposed Solution
Implement a comprehensive set of Kubernetes NetworkPolicies based on the actual observed traffic patterns:

1. **Default Deny All Policy**:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: detection-demo
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

2. **Allow Only Necessary Internal Traffic**:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-app-traffic
  namespace: detection-demo
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8080
```

3. **Allow Specific External Traffic for SSRF App**:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ssrf-app-network-policy
  namespace: detection-demo
spec:
  podSelector:
    matchLabels:
      app: ssrf-vulnerable-app
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 151.101.0.0/16
    ports:
    - protocol: TCP
      port: 443
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
```

## Impact
- High: Implementing proper network policies is critical for preventing lateral movement
- Will require monitoring after implementation to ensure no legitimate traffic is blocked

## Tasks
- [ ] Document all legitimate network communication paths
- [ ] Create and apply the network policies in a staged approach
- [ ] Monitor for any disruptions to legitimate application traffic
- [ ] Block port 4444 communication explicitly
- [ ] Add monitoring for policy violations
- [ ] Document exceptions and their justifications
- [ ] Create a process for reviewing and updating network policies

## Technical Notes
- Focus on the `detection-demo` namespace first
- Ensure DNS access is preserved for all applications
- Consider implementing Cilium for more advanced network policy capabilities
- Monitor network policy logs for denied traffic to identify potential issues or attacks
