### ISSUE TITLE
NetworkPolicy to Block PII Exfiltration

### ISSUE THREAD

**Issue by ksoc-automator** [rad-security/kbom#165]
### Summary
Our monitoring has detected PII data being transmitted from pods in the `default` namespace to suspicious external domains, including unencrypted HTTP traffic to a Russian domain. This issue provides a NetworkPolicy to block this suspicious traffic.

### Detected PII Movement

We identified 7 instances of HTTP requests containing PII data across the environment:

1. **Types of PII detected:**
   - Names
   - Email addresses
   - Physical addresses
   - Credit card information
   - Bank account numbers
   - Driver's licenses

2. **Source workloads transmitting PII:**
   - `rw-test` pod in the default namespace
   - `pii-container` pod in the default namespace
   - `test-http` pod in the default namespace

3. **Suspicious patterns:**
   - Connection to "RLSBB.ru" over unencrypted HTTP (port 80) - Russian domain receiving PII data
   - One request from `rw-test` pod included credit card and bank number data
   - Multiple connections to external domains transferring PII

### Remediation: NetworkPolicy

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-pii-exfiltration
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: pii-protection
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow traffic to whitelisted destinations only
  - to:
    - ipBlock:
        # Internal cluster IPs
        cidr: 10.0.0.0/8
    - ipBlock:
        # Allow legitimate business domains only
        cidr: 0.0.0.0/0
        except:
        - 104.21.30.184/32  # RLSBB.ru
        - 104.19.222.17/32  # Suspicious destination IP
    ports:
    - protocol: TCP
      port: 443  # Allow only HTTPS traffic
```

### Implementation Steps:

1. **Label the affected pods**:
```bash
kubectl label pod rw-test app.kubernetes.io/component=pii-protection -n default
kubectl label pod pii-container app.kubernetes.io/component=pii-protection -n default
kubectl label pod test-http app.kubernetes.io/component=pii-protection -n default
```

2. **Apply the NetworkPolicy**:
```bash
kubectl apply -f block-pii-exfiltration.yaml
```

### How this NetworkPolicy works:

1. **Targeted Protection**: It applies only to pods labeled with `app.kubernetes.io/component=pii-protection`
2. **DNS Resolution**: It allows UDP traffic to port 53 in the kube-system namespace
3. **Internal Traffic**: It permits traffic to internal cluster IPs (10.0.0.0/8)
4. **Blocked External IPs**: It explicitly blocks traffic to the suspicious IPs identified
5. **HTTPS Only**: It only allows outbound TCP traffic on port 443 (HTTPS), blocking unencrypted HTTP traffic

### Additional Recommendations:

1. **Implement admission control**: Use OPA Gatekeeper to ensure new pods handling PII have appropriate security controls
2. **Enhanced monitoring**: Set up alerts for any attempted connections to blocked IPs
3. **Data Loss Prevention**: Consider implementing a DLP solution to inspect and block traffic containing PII

cc: @security-team
